CREATE TABLE users
(
	ID VARCHAR2(12) PRIMARY KEY,
	PW VARCHAR2(20),
	NAME VARCHAR2(20)
)

CREATE TABLE orders(
   PRODUCT_NUM NUMBER PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(100),
   PRODUCT_PRICE NUMBER,
   ORDER_ID VARCHAR2(50),
   CONSTRAINT ORDERS_FK FOREIGN KEY(ORDER_ID) REFERENCES USERS(ID)
)

INSERT INTO orders VALUES('1', '빼빼로', 2000, 'system');